filebeat.inputs:
  - type: filestream
    id: nginx-access
    enabled: true
    paths:
      - /var/log/nginx/access.log

  - type: filestream
    id: nginx-error
    enabled: true
    paths:
      - /var/log/nginx/error.log

output.logstash:
  hosts: ["logstash:5044"]
